"use client";
import { useEffect,useMemo,useState } from "react";
import { useReducedMotion } from "motion/react";
export function FlowCycle({steps,speed=80,holdTime=1600,deleteSpeed=40}:{steps:string[];speed?:number;holdTime?:number;deleteSpeed?:number}){
 const reduced=useReducedMotion();const original=steps.join(" → ");const cmsKey=`animated:flow:${original}`;const [items,setItems]=useState(steps);const [factor,setFactor]=useState(1);const [index,setIndex]=useState(0);const [chars,setChars]=useState(reduced?steps[0]?.length||0:0);const active=items[index%Math.max(items.length,1)]||"";
 useEffect(()=>{const text=(e:Event)=>{const d=(e as CustomEvent<{key:string;value:string}>).detail;if(d?.key===cmsKey){const next=d.value.split(/\s*(?:→|,|\n)\s*/).filter(Boolean);if(next.length){setItems(next);setIndex(0);setChars(0)}}};const pace=(e:Event)=>{const d=(e as CustomEvent<{key:string;speed:number}>).detail;if(d?.key===cmsKey)setFactor(d.speed>0?d.speed:1)};document.addEventListener("cms:animated-text",text);document.addEventListener("cms:animation-speed",pace);return()=>{document.removeEventListener("cms:animated-text",text);document.removeEventListener("cms:animation-speed",pace)}},[cmsKey]);
 useEffect(()=>{if(reduced)return;let timer:ReturnType<typeof setTimeout>;if(chars<active.length)timer=setTimeout(()=>setChars(x=>x+1),speed/factor);else timer=setTimeout(()=>{setIndex(x=>(x+1)%items.length);setChars(0)},holdTime/factor);return()=>clearTimeout(timer)},[active,chars,deleteSpeed,factor,holdTime,items.length,reduced,speed]);
 const shown=reduced?active.length:chars;const value=useMemo(()=>items.join(" → "),[items]);return <div className="min-h-7 font-[family-name:var(--font-display)] text-sm font-semibold tracking-tight text-gold-500" data-cms-key={cmsKey} data-cms-kind="text" data-cms-animated="true" data-cms-original={original} data-cms-current={value}><span>{active.slice(0,shown)}</span><span aria-hidden className="ml-0.5 inline-block h-[.85em] w-[.06em] translate-y-[.08em] animate-caret bg-gold-500"/></div>
}
