"use client";

import { ChangeEvent, FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { Building2, Check, ImagePlus, Layers3, Loader2, Pencil, Plus, Trash2, Upload, X } from "lucide-react";
import { API_URL, apiRequest } from "@/lib/api/client";

type Kind="logo"|"project"|"section";
type Item={id:string;locale:string;key:string;title:string;type:Kind;status:string;data:string;updatedAt:string};
type Media={url:string;name:string};
type Draft={id?:string;locale:string;key:string;title:string;type:Kind;status:string;fields:Record<string,string>};
const pages=[["Home","/"],["About","/about"],["How it works","/how-it-works"],["Services","/services"],["Products","/products"],["Stock plans","/products/stock-plans"],["Blog","/blog"],["Careers","/careers"],["Contact","/contact"],["FAQ","/faq"],["Resources","/resources"]];
const origin=API_URL.replace(/\/api\/v1\/?$/,"");
const asset=(url:string)=>/^(https?:|data:|blob:)/.test(url)?url:`${origin}${url}`;
const empty=(type:Kind):Draft=>({locale:"en",key:`${type}-${Date.now()}`,title:"",type,status:"published",fields:type==="logo"?{image:"",website:""}:type==="project"?{image:"",description:"",location:"",category:"Featured project",path:"/"}:{eyebrow:"",body:"",image:"",layout:"image-right",path:"/",ctaLabel:"",ctaUrl:""}});

export default function ContentStudio({token,flash}:{token:string;flash:(s:string)=>void}){
  const [kind,setKind]=useState<Kind>("logo");const [items,setItems]=useState<Item[]>([]);const [draft,setDraft]=useState<Draft|null>(null);const [busy,setBusy]=useState(false);
  const load=useCallback(()=>apiRequest<{items:Item[]}>("/admin/contents?size=100",{},token).then(x=>setItems(x.items)),[token]);useEffect(()=>{load()},[load]);
  const shown=useMemo(()=>items.filter(x=>x.type===kind),[items,kind]);
  const edit=(item:Item)=>{let fields={};try{fields=JSON.parse(item.data)}catch{}setDraft({...item,type:item.type,fields})};
  const field=(key:string,value:string)=>setDraft(old=>old?{...old,fields:{...old.fields,[key]:value}}:old);
  async function upload(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;setBusy(true);try{const body=new FormData();body.append("file",file);const media=await apiRequest<Media>("/admin/media",{method:"POST",body},token);field("image",media.url);flash("Image uploaded")}finally{setBusy(false);e.target.value=""}}
  async function save(e:FormEvent){e.preventDefault();if(!draft)return;setBusy(true);try{const payload={locale:draft.locale,key:draft.key,title:draft.title,type:draft.type,status:draft.status,data:JSON.stringify(draft.fields)};await apiRequest(draft.id?`/admin/contents/${draft.id}`:"/admin/contents",{method:draft.id?"PUT":"POST",body:JSON.stringify(payload)},token);setDraft(null);await load();flash(`${draft.type==="logo"?"Logo":draft.type==="project"?"Project":"Page section"} saved and published`)}finally{setBusy(false)}}
  async function remove(id:string){if(!confirm("Delete this item permanently?"))return;await apiRequest(`/admin/contents/${id}`,{method:"DELETE"},token);load();flash("Content deleted")}
  const tabs:[Kind,string,React.ElementType,string][]=[["logo","Client logos",ImagePlus,"Trust badges and partner logos"],["project","Projects",Building2,"Portfolio work and case studies"],["section","Page sections",Layers3,"Add new text and image sections"]];
  return <div className="mx-auto max-w-7xl"><section className="rounded-[2rem] bg-[#071027] p-7 text-white sm:p-9"><p className="text-sm font-bold text-orange-400">Content Studio</p><h2 className="mt-2 text-3xl font-bold">Build and grow your website.</h2><p className="mt-3 max-w-2xl text-slate-400">Add logos, showcase projects, and publish complete new sections without touching code or JSON.</p></section>
    <div className="mt-6 grid gap-3 md:grid-cols-3">{tabs.map(([id,label,Icon,help])=><button key={id} onClick={()=>setKind(id)} className={`rounded-2xl border p-5 text-left transition ${kind===id?"border-orange-400 bg-orange-50 shadow-sm":"border-slate-200 bg-white hover:border-slate-300"}`}><Icon className={`size-6 ${kind===id?"text-orange-600":"text-slate-400"}`}/><p className="mt-3 font-bold">{label}</p><p className="mt-1 text-xs text-slate-500">{help}</p></button>)}</div>
    <div className="mt-7 flex items-end justify-between"><div><h3 className="text-2xl font-bold">{tabs.find(x=>x[0]===kind)?.[1]}</h3><p className="mt-1 text-sm text-slate-500">{shown.length} items · Draft or publish at any time</p></div><button onClick={()=>setDraft(empty(kind))} className="flex items-center gap-2 rounded-xl bg-orange-500 px-5 py-3 text-sm font-bold text-white shadow-sm hover:bg-orange-600"><Plus className="size-4"/>Add new</button></div>
    <div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{shown.map(item=>{let data:Record<string,string>={};try{data=JSON.parse(item.data)}catch{}return <article key={item.id} className="group overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">{data.image?<div className={`overflow-hidden bg-slate-100 ${kind==="logo"?"grid aspect-[2/1] place-items-center p-6":"aspect-video"}`}><img src={asset(data.image)} alt={item.title} className={kind==="logo"?"max-h-full max-w-full object-contain":"h-full w-full object-cover"}/></div>:<div className="grid aspect-video place-items-center bg-slate-100"><ImagePlus className="size-9 text-slate-300"/></div>}<div className="p-5"><div className="flex items-start justify-between gap-3"><div><p className="font-bold">{item.title}</p><p className="mt-1 text-xs uppercase tracking-wider text-slate-400">{item.locale} · {item.status}</p></div><span className={`size-2.5 rounded-full ${item.status==="published"?"bg-emerald-500":"bg-amber-400"}`}/></div>{data.description&&<p className="mt-3 line-clamp-2 text-sm text-slate-500">{data.description}</p>}<div className="mt-4 flex gap-2"><button onClick={()=>edit(item)} className="flex flex-1 items-center justify-center gap-2 rounded-lg bg-slate-100 py-2 text-xs font-bold hover:bg-slate-200"><Pencil className="size-3.5"/>Edit</button><button onClick={()=>remove(item.id)} className="rounded-lg p-2 text-red-500 hover:bg-red-50"><Trash2 className="size-4"/></button></div></div></article>})}{!shown.length&&<div className="col-span-full rounded-2xl border border-dashed border-slate-300 bg-white py-16 text-center"><Plus className="mx-auto size-8 text-slate-300"/><p className="mt-3 font-bold">Add your first {kind}</p><p className="mt-1 text-sm text-slate-400">It will appear on the live website after publishing.</p></div>}</div>
    {draft&&<div className="fixed inset-0 z-50 grid place-items-center bg-[#071027]/70 p-4 backdrop-blur-sm"><form onSubmit={save} className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-3xl bg-white shadow-2xl"><header className="sticky top-0 z-10 flex items-center justify-between border-b bg-white px-6 py-5"><div><p className="text-xs font-bold uppercase tracking-widest text-orange-600">{draft.type}</p><h3 className="text-xl font-bold">{draft.id?"Edit":"Add new"} {draft.type}</h3></div><button type="button" onClick={()=>setDraft(null)} className="rounded-lg p-2 hover:bg-slate-100"><X/></button></header><div className="grid gap-5 p-6">
      <label className="text-sm font-bold">{draft.type==="logo"?"Company / organization name":draft.type==="project"?"Project title":"Section heading"}<input required value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 outline-none focus:border-orange-400"/></label>
      <div className="grid grid-cols-2 gap-4"><label className="text-sm font-bold">Language<select value={draft.locale} onChange={e=>setDraft({...draft,locale:e.target.value})} className="mt-2 h-11 w-full rounded-xl border border-slate-200 bg-white px-3"><option value="en">English</option><option value="es">Spanish</option></select></label><label className="text-sm font-bold">Status<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})} className="mt-2 h-11 w-full rounded-xl border border-slate-200 bg-white px-3"><option value="published">Published</option><option value="draft">Draft</option></select></label></div>
      {draft.type!=="logo"&&<label className="text-sm font-bold">Show on page<select value={draft.fields.path} onChange={e=>field("path",e.target.value)} className="mt-2 h-11 w-full rounded-xl border border-slate-200 bg-white px-3">{pages.map(([name,path])=><option key={path} value={path}>{name}</option>)}</select></label>}
      {draft.type==="section"&&<><label className="text-sm font-bold">Small heading / eyebrow<input value={draft.fields.eyebrow} onChange={e=>field("eyebrow",e.target.value)} className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3"/></label><label className="text-sm font-bold">Section text<textarea required rows={6} value={draft.fields.body} onChange={e=>field("body",e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 p-3"/></label><label className="text-sm font-bold">Layout<select value={draft.fields.layout} onChange={e=>field("layout",e.target.value)} className="mt-2 h-11 w-full rounded-xl border border-slate-200 bg-white px-3"><option value="image-right">Text left · image right</option><option value="image-left">Image left · text right</option><option value="centered">Centered content</option></select></label><div className="grid grid-cols-2 gap-4"><label className="text-sm font-bold">Button label<input value={draft.fields.ctaLabel} onChange={e=>field("ctaLabel",e.target.value)} className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3"/></label><label className="text-sm font-bold">Button URL<input value={draft.fields.ctaUrl} onChange={e=>field("ctaUrl",e.target.value)} className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3"/></label></div></>}
      {draft.type==="project"&&<><label className="text-sm font-bold">Description<textarea required rows={5} value={draft.fields.description} onChange={e=>field("description",e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 p-3"/></label><div className="grid grid-cols-2 gap-4"><label className="text-sm font-bold">Category<input value={draft.fields.category} onChange={e=>field("category",e.target.value)} className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3"/></label><label className="text-sm font-bold">Location<input value={draft.fields.location} onChange={e=>field("location",e.target.value)} className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3"/></label></div></>}
      {draft.type==="logo"&&<label className="text-sm font-bold">Website URL<input value={draft.fields.website} onChange={e=>field("website",e.target.value)} className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3"/></label>}
      <label className="text-sm font-bold">{draft.type==="logo"?"Logo":"Image"}<div className="mt-2 flex gap-2"><input value={draft.fields.image} onChange={e=>field("image",e.target.value)} placeholder="Image URL" className="h-11 min-w-0 flex-1 rounded-xl border border-slate-200 px-3"/><label className="flex cursor-pointer items-center gap-2 rounded-xl bg-orange-50 px-4 text-xs font-bold text-orange-700"><Upload className="size-4"/>{busy?"Uploading":"Upload"}<input type="file" accept="image/*,.svg" onChange={upload} className="hidden"/></label></div></label>
      <button disabled={busy} className="flex h-12 items-center justify-center gap-2 rounded-xl bg-[#071027] font-bold text-white disabled:opacity-50">{busy?<Loader2 className="size-5 animate-spin"/>:<Check className="size-5"/>}Save and publish</button>
    </div></form></div>}
  </div>
}
