"use client";

import { useCallback, useEffect, useMemo, useState, type ElementType } from "react";
import { CalendarDays, CheckCircle2, ChevronRight, Clock3, Download, Inbox, Mail, MapPin, Phone, Search, Trash2, UserRound, X } from "lucide-react";
import { apiRequest } from "@/lib/api/client";

type Lead={id:string;name:string;company:string;phone:string;email:string;referral:string;address:string;timeline:string;budget:string;county:string;city:string;state:string;postalCode:string;phase:string;projectType:string;services:string;message:string;deadline:string;language:string;status:string;notes:string;createdAt:string};
const statuses=["all","new","contacted","qualified","proposal","won","lost"];

export default function SubmissionsInbox({token,flash}:{token:string;flash:(s:string)=>void}){
  const [items,setItems]=useState<Lead[]>([]);const [selected,setSelected]=useState<Lead|null>(null);const [query,setQuery]=useState("");const [status,setStatus]=useState("all");
  const load=useCallback(()=>apiRequest<{items:Lead[]}>("/admin/leads?limit=100",{},token).then(x=>setItems(x.items)),[token]);useEffect(()=>{load()},[load]);
  const shown=useMemo(()=>items.filter(x=>(status==="all"||x.status===status)&&`${x.name} ${x.email} ${x.phone} ${x.company} ${x.message}`.toLowerCase().includes(query.toLowerCase())),[items,query,status]);
  const counts={all:items.length,new:items.filter(x=>x.status==="new").length,active:items.filter(x=>["contacted","qualified","proposal"].includes(x.status)).length,won:items.filter(x=>x.status==="won").length};
  const summaryCards:[string,number,ElementType,string][]=[["All submissions",counts.all,Inbox,"bg-blue-50 text-blue-600"],["New",counts.new,Mail,"bg-orange-50 text-orange-600"],["In progress",counts.active,Clock3,"bg-violet-50 text-violet-600"],["Won",counts.won,CheckCircle2,"bg-emerald-50 text-emerald-600"]];
  async function update(lead:Lead,nextStatus:string,notes:string){await apiRequest(`/admin/leads/${lead.id}`,{method:"PATCH",body:JSON.stringify({status:nextStatus,notes})},token);await load();setSelected(null);flash("Submission updated")}
  async function remove(lead:Lead){if(!confirm(`Delete the submission from ${lead.name}?`))return;await apiRequest(`/admin/leads/${lead.id}`,{method:"DELETE"},token);setSelected(null);load();flash("Submission deleted")}
  function exportCsv(){const keys:(keyof Lead)[]=["createdAt","name","email","phone","company","projectType","services","budget","timeline","address","city","county","state","postalCode","message","status","notes"];const quote=(v:unknown)=>`"${String(v??"").replaceAll('"','""')}"`;const csv=[keys.join(","),...shown.map(row=>keys.map(k=>quote(row[k])).join(","))].join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download=`builderstech-submissions-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href)}
  return <div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-bold uppercase tracking-[.18em] text-orange-600">Customer inbox</p><h2 className="mt-1 text-3xl font-bold">Form submissions</h2><p className="mt-2 text-sm text-slate-500">Every contact and project intake form arrives here automatically.</p></div><button onClick={exportCsv} className="flex items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-bold hover:bg-slate-50"><Download className="size-4"/>Export CSV</button></div>
    <div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{summaryCards.map(([label,value,Icon,color])=><div key={label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className={`grid size-10 place-items-center rounded-xl ${color}`}><Icon className="size-5"/></div><p className="mt-4 text-3xl font-bold">{value}</p><p className="mt-1 text-sm text-slate-500">{label}</p></div>)}</div>
    <div className="mt-6 rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-slate-100 p-4 lg:flex-row lg:items-center"><label className="relative flex-1"><Search className="absolute left-3 top-3 size-4 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, email, phone, company…" className="h-10 w-full rounded-xl border border-slate-200 pl-10 pr-3 text-sm outline-none focus:border-orange-400"/></label><div className="flex gap-2 overflow-x-auto">{statuses.map(x=><button key={x} onClick={()=>setStatus(x)} className={`whitespace-nowrap rounded-lg px-3 py-2 text-xs font-bold capitalize ${status===x?"bg-[#071027] text-white":"bg-slate-100 text-slate-500"}`}>{x}</button>)}</div></div>
      <div className="divide-y divide-slate-100">{shown.map(x=><button key={x.id} onClick={()=>setSelected(x)} className="flex w-full items-center gap-4 p-5 text-left transition hover:bg-slate-50"><div className="grid size-11 shrink-0 place-items-center rounded-xl bg-orange-50 font-bold text-orange-600">{x.name.slice(0,1).toUpperCase()}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-bold">{x.name}</p><Status value={x.status}/>{x.language&&<span className="text-xs font-bold uppercase text-slate-400">{x.language}</span>}</div><p className="mt-1 truncate text-sm text-slate-500">{x.email} · {x.phone||"No phone"} · {x.projectType||"General inquiry"}</p><p className="mt-2 line-clamp-1 text-sm text-slate-600">{x.message}</p></div><div className="hidden text-right sm:block"><p className="text-xs font-semibold text-slate-500">{new Date(x.createdAt).toLocaleDateString()}</p><p className="mt-1 text-xs text-slate-400">{new Date(x.createdAt).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</p></div><ChevronRight className="size-5 shrink-0 text-slate-300"/></button>)}{!shown.length&&<div className="py-20 text-center"><Inbox className="mx-auto size-10 text-slate-300"/><p className="mt-3 font-bold">No submissions found</p><p className="mt-1 text-sm text-slate-400">New contact forms will appear here automatically.</p></div>}</div>
    </div>
    {selected&&<div className="fixed inset-0 z-50 bg-[#071027]/60 backdrop-blur-sm" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><aside className="absolute inset-y-0 right-0 w-full max-w-xl overflow-y-auto bg-white shadow-2xl"><header className="sticky top-0 z-10 flex items-center justify-between border-b bg-white px-6 py-5"><div><p className="text-xs font-bold uppercase tracking-widest text-orange-600">Form submission</p><h3 className="mt-1 text-xl font-bold">{selected.name}</h3></div><button onClick={()=>setSelected(null)} className="rounded-lg p-2 hover:bg-slate-100"><X/></button></header><div className="space-y-6 p-6"><div className="grid gap-3 sm:grid-cols-2"><Info icon={Mail} label="Email" value={selected.email}/><Info icon={Phone} label="Phone" value={selected.phone}/><Info icon={UserRound} label="Company" value={selected.company}/><Info icon={CalendarDays} label="Submitted" value={new Date(selected.createdAt).toLocaleString()}/><Info icon={MapPin} label="Location" value={[selected.address,selected.city,[selected.state,selected.postalCode].filter(Boolean).join(" "),selected.county&&`${selected.county} County`].filter(Boolean).join(", ")}/><Info icon={Clock3} label="Timeline / deadline" value={[selected.timeline,selected.deadline].filter(Boolean).join(" · ")}/></div><Details label="Project type" value={selected.projectType}/><Details label="Services requested" value={selected.services}/><div className="grid gap-4 sm:grid-cols-2"><Details label="Budget" value={selected.budget}/><Details label="Project phase" value={selected.phase}/></div><Details label="How they found us" value={selected.referral}/><Details label="Message" value={selected.message}/><label className="block text-sm font-bold">Pipeline status<select id="submission-status" defaultValue={selected.status} className="mt-2 h-11 w-full rounded-xl border border-slate-200 bg-white px-3">{statuses.slice(1).map(x=><option key={x}>{x}</option>)}</select></label><label className="block text-sm font-bold">Internal notes<textarea id="submission-notes" defaultValue={selected.notes} rows={5} className="mt-2 w-full rounded-xl border border-slate-200 p-3"/></label><button onClick={()=>update(selected,(document.getElementById("submission-status") as HTMLSelectElement).value,(document.getElementById("submission-notes") as HTMLTextAreaElement).value)} className="h-12 w-full rounded-xl bg-[#071027] font-bold text-white">Save submission</button><button onClick={()=>remove(selected)} className="flex h-11 w-full items-center justify-center gap-2 rounded-xl text-sm font-bold text-red-600 hover:bg-red-50"><Trash2 className="size-4"/>Delete submission</button></div></aside></div>}
  </div>
}
function Status({value}:{value:string}){const color=value==="new"?"bg-orange-50 text-orange-700":value==="won"?"bg-emerald-50 text-emerald-700":value==="lost"?"bg-red-50 text-red-700":"bg-blue-50 text-blue-700";return <span className={`rounded-full px-2.5 py-1 text-[11px] font-bold capitalize ${color}`}>{value}</span>}
function Info({icon:Icon,label,value}:{icon:React.ElementType;label:string;value:string}){return <div className="rounded-xl bg-slate-50 p-4"><Icon className="size-4 text-orange-500"/><p className="mt-2 text-xs font-bold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 break-words text-sm font-semibold">{value||"—"}</p></div>}
function Details({label,value}:{label:string;value:string}){return <div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-700">{value||"—"}</p></div>}
